### ISSUE TITLE
Some ideas/fixes/etc

### ISSUE THREAD

**Issue by chenriquevz** [dgsdestinygamestudios/godot-google-play-billing#1]
Hey, thank you for doing this upgrade!

I have been trying to make an IAP work for a course that I am doing and I faced some issues. I created a gist that is still a WIP if you like to consider as a candidate to be added to your work.

`_on_purchases_response` as per the google recommendation we should query `on_resume` (android lifecycle) to check if any purchase has been made outside of our app, like in the web, or even on another phone linked to the same account. 

In any case, without the changes I have made everytime we receive a response new purchases are being added to the `_purchases`. I believe `if not object in _purchases:` is not doing what we expect to do, as I am not aware of how to make a object `equal` evalution like we have in java/kotlin, I decided to check if the token is already appended to `_purchases`.

I have also added a check to try to acknowledge purchases that are with the `PURCHASED` status but not acknowledged.

`_on_purchases_updated` without the changed I have made it was not possible to properly acknowledge the purchases, I believe it was a typo trying to find tokens on const that suppose to have skus.

I have not tested slow payments/decline payments/subscriptions/etc, only regular purchases.

https://gist.github.com/chenriquevz/58f4544ecd2496323eaf4a9f25ede863

edit: google document regarding "on resume".
https://developer.android.com/google/play/billing/integrate#fetch

edit: I have also removed `_connect_signals` and `_start_connection` from ready() because I wanted to control when to start. I notice right now that I left my logging class on the code, anyway it is a draft :D

**Comment by dgsdestinygamestudios** [comment]
Hello,

I have added `resume` callback. Thank you for pointing that out.

Getting duplicate objects after querying is now fixed. Rather than checking if object is in the array, now array clears itself. Which sounds more logical to me.

Starting connection immediately should be the default case of the plugin. But of course, you can change it however you want for your own use.

Rather than adding signal `setup_completed(response_code: ResponseCode)` , you can check with `await Billing._library.setup_finished`.

Same goes for the signal `purchase_completed(purchase_token: String)`. You can reward player in the `_handle_purchase(purchase_token: String)` function with a match case.

Example:
```
func _handle_purchase(purchase_token: String) -> void:
	print("[Billing]: Rewarding player!\n\tPurchase Token: %s" % purchase_token)
	_latest_purchase_token = ""
        match purchase_token:
                "token":
                        print("[Billing]: Token rewarded!")
```

Please check the changes and test if things are good. And don't forget to let me know.

Thank you for your message.

**Comment by chenriquevz** [comment]
Thanks for the reply!

I think you made good decisions there! I did remove the ready because starting everything on ready() was crashing my logging class/auto load (or something like that) I was also thinking about exploring the samsung store and in that case I believe I would not use the google IAP even it being an android and it would most likely have the singleton avaiable? I am not sure. (in any case I am not saying you should change!).

(I will randomly talk additional stuff that I think can be better but keep in mind that I am new to godot in general and I dont even know if you wanna keep this code open to changes/fixes - in any case this conversation can be used by others?! Anyway, trying to share what I did on my end - I am still testing stuff). I also made a fork of your repo I will try to upload my version latter just to have it saved somewhere.

About `GodotGooglePlayBilling.java` I think it would be best to change the signal on line 261 from `("purchases_response",` to something like `query_purchase_response` as it stand at least for me is confusing, because in the `Billing.gd` we have `_on_purchase` and `_on_purchase_response` being the last one regarding to a query not a purchase. Likewise I think would be best to change to something like `on_query_purchase_response`

Also on the java file, I think would be good to add an error handling (aka emit signal) whenever we try to return on `Purchase` because something wasnt ok?! 

I am not sure if the `last_token_purchase` strategy will work in some edge cases I believe it is possible that with some connection issues and whatnot we end up acknowledging a purchase by mistake, or maybe the user makes a purchase that is slow to approve and a second one that is instantaneous?! Maybe we will override a `_latest_purchase_token` in this case?

With that being said, I think peharps is better to grant access when you try to consume/acknowledge? With this method I believe it is possible to grant access before acknowleding and an ill intent user could cut connection to never send an ack to google to have them refund in 3 days? But I mean, if people wanna cheat they will crack the app, no?! With consumables I belive they would be able to receive multiple "coins" with one purchase?! But again, easier to crack the app and do whatever they want?

edit: just to add to this last bit, I notice that when we ack a non consumable purchase google doesnt answer a token, but when it is a consumable answer they do. Maybe it is their way to tell that it doesnt matter ack to "skin" but it does for "coins? I mean, at least in my head makes sense. That being said I think a dictionary to hold the on going consumable purchases is a good start (and only granting the consumable whenever the consume_response is done).

**Comment by dgsdestinygamestudios** [comment]
Hello,

We could change `_latest_purchase_token` field into a string array rather than a single string. That way, we can store every token that gets a call for purchase. And when acknowledging is finished, we can remove the token from the array.

We can rename `_on_purchase` to `_on_purchase_attempt`, as it gets called, for example, when the user clicks a button to purchase. Other than that, the signal has no big use. It's just for test. We could remove it altogether without any issue.

I can leave the code open for changes, if changes make sense. I'm not a perfect programmer, so I'm bound to make mistakes, and other people could fix them. We have our backs here :D

Thank you for getting back to me. Now let me check what I can do about the things we talked about.

**EDIT**

I have made some changes. Check and let me know if there are any issues, please.

`acknowledge_purchase_response` now returns the acknowledged token. Safer than putting them into an array.
Renamed `purchase` to `purchase_attempt`
Renamed `purchases_response` to `query_purchases_response`
Handling consumables are done in a different function to handle the quantity of the purchase.
